services:
  wa-gateway:
    container_name: wa-gateway
    restart: unless-stopped

    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "5001:5001"

    environment:
      #KEY: ""
      NODE_ENV: production

    volumes:
      - ./wa_credentials:/app/wa_credentials
      - ./media:/app/media
